import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {Contract,Interface,EventLog,UndecodedEventLog,Log} from 'quais';
const f=JSON.parse(readFileSync(new URL('../fixtures/contract-io.json',import.meta.url)));
test('published fallback receive matrix selects payable data/value paths',async()=>{assert.equal(f.vectors.length,24);for(const row of f.vectors){const contract=new Contract(f.address,row.abi);if(!contract.fallback){assert.equal(row.expected,null);continue;}if(row.expected===null)await assert.rejects(contract.fallback.populateTransaction({data:row.data,value:BigInt(row.value)}));else{const tx=await contract.fallback.populateTransaction({data:row.data,value:BigInt(row.value)});assert.equal(tx.data,row.expected.data);assert.equal(String(tx.value),row.expected.value);assert.equal(tx.to,row.expected.to);}}});
test('published fallback simulation and estimation return raw results, bindings are explicit',async()=>{const calls=[];const runner={call:async tx=>{calls.push(tx);return '0xbeef';},estimateGas:async tx=>{calls.push(tx);return 21000n;}};const contract=new Contract(f.address,[{type:'fallback',stateMutability:'payable'}],runner);assert.equal(await contract.fallback.staticCall({data:'0x1234',value:1n}),'0xbeef');assert.equal(await contract.fallback.estimateGas({data:'0x1234',value:1n}),21000n);assert.equal(calls.length,2);assert.equal(calls[0].data,'0x1234');const other=contract.attach('0x0000000000000000000000000000000000000001');assert.equal(await other.getAddress(),'0x0000000000000000000000000000000000000001');const next=contract.connect(runner);assert.equal(next.interface,contract.interface);});
test('published wildcard event queries retain unknown and malformed logs; queryTransaction is TODO',async()=>{const iface=new Interface(['event Ping(uint n)']);const encoded=iface.encodeEventLog('Ping',[7]);const common={address:f.address,blockHash:'0x'+'11'.repeat(32),blockNumber:10,transactionHash:'0x'+'22'.repeat(32),transactionIndex:0,removed:true};const rows=[{...common,index:0,...encoded},{...common,index:1,data:'0x',topics:[]},{...common,index:2,data:'0x01',topics:encoded.topics}];const provider={getLogs:async()=>rows};const contract=new Contract(f.address,iface,{provider});const logs=await contract.queryFilter('*',10,20);assert.ok(logs[0] instanceof EventLog);assert.ok(logs[1] instanceof Log);assert.ok(!(logs[1] instanceof EventLog));assert.ok(logs[2] instanceof UndecodedEventLog);assert.equal(logs[0].args[0],7n);assert.equal(logs[2].data,'0x01');await assert.rejects(contract.queryTransaction(common.transactionHash),/@TODO/);});

test('published receive flag is overwritten by later nonpayable fallback',()=>{const receive={type:'receive',stateMutability:'payable'},fallback={type:'fallback',stateMutability:'nonpayable'};assert.equal(new Interface([receive,fallback]).receive,false);assert.equal(new Interface([fallback,receive]).receive,true);assert.equal(f.vectors.filter(v=>v.difference).length,1);});
test('published waitForDeployment can wait for code with no deployment transaction hash',async()=>{let reads=0,blocks=0;const provider={getCode:async()=>++reads<3?'0x':'0x6000',once:async(event,listener)=>{assert.equal(event,'block');blocks++;queueMicrotask(listener);}};const contract=new Contract(f.address,[],{provider});assert.equal(contract.deploymentTransaction(),null);assert.equal(await contract.waitForDeployment(),contract);assert.equal(reads,3);assert.equal(blocks,1);});
