import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {QuaiTransaction,QiTransaction,accessListify,getBytes,hexlify,encodeProtoTransaction,decodeProtoTransaction} from 'quais';
const f=JSON.parse(readFileSync(new URL('../fixtures/transactions.json',import.meta.url))).vectors;
const convert=JSON.parse(readFileSync(new URL('../../crates/quai-consensus/tests/conversion-vectors.json',import.meta.url))).vectors;
const wrap=JSON.parse(readFileSync(new URL('../../crates/quai-consensus/tests/wrapping-vectors.json',import.meta.url))).vectors;
test('published typed wire roundtrips preserve bytes while raw protobuf decoding inserts absent defaults',()=>{for(const row of [...f,...convert,...wrap]){for(const key of ['signed','unsigned'])assert.notEqual(encodeProtoTransaction(decodeProtoTransaction(getBytes(row[key]))),row[key]);const cls=row.input.txInputs?QiTransaction:QuaiTransaction;const tx=cls.from(row.signed);assert.equal(tx.serialized,row.signed);assert.equal(tx.digest,row.digest);assert.equal(tx.hash,row.hash);}});
test('published JSON constructors ignore supplied signed hash and do not verify Qi signatures',()=>{for(const row of f.filter(x=>x.kind==='quai'||x.id==='qi-0')){const cls=row.kind==='quai'?QuaiTransaction:QiTransaction;const tx=cls.from({...row.input,hash:'0x'+'ff'.repeat(32)});assert.notEqual(tx.hash,'0x'+'ff'.repeat(32));}const row=f.find(x=>x.id==='qi-0');const tx=QiTransaction.from({...row.input,signature:'0x'+'00'.repeat(64)});assert.equal(tx.isSigned(),true);assert.equal(tx.signature,'0x'+'00'.repeat(64));});
test('published Qi JSON hex data is coerced as a typed-array length, and output locks are discarded by re-encoding',()=>{const row=convert.find(x=>x.input.txInputs);assert.throws(()=>QiTransaction.from(row.input),RangeError);const qi=QiTransaction.from(f.find(x=>x.id==='qi-0').signed);const proto=qi.toProtobuf();proto.tx_outs.tx_outs[0].lock=getBytes('0x01');const encoded=encodeProtoTransaction(proto);const restored=QiTransaction.from(encoded);assert.equal(restored.txOutputs[0].lock,'0x01');assert.notEqual(restored.serialized,encoded);assert.equal(hexlify(restored.toProtobuf().tx_outs.tx_outs[0].lock),'0x');});
test('published map access-list deduplication precedes hex-case normalization; arrays preserve duplicates and order',()=>{const addr='0x0011223344556677889900112233445566778899';const lower='0x'+'ab'.repeat(32),upper='0x'+'AB'.repeat(32);assert.deepEqual(accessListify({[addr]:[upper,lower,upper]})[0].storageKeys,[lower,lower]);assert.deepEqual(accessListify([[addr,[upper,lower,upper]]])[0].storageKeys,[lower,lower,lower]);assert.throws(()=>accessListify([[addr,[],123]]));});
