import test from 'node:test';import assert from 'node:assert/strict';
import {ContractTransactionResponse,Interface,EventPayload} from 'quais';
import {QuaiTransactionResponse,QiTransactionResponse} from '../node_modules/quais/lib/esm/providers/provider.js';
import * as publicQuais from 'quais';
const hash='0x00800080'+'11'.repeat(28),blockHash='0x'+'22'.repeat(32);
const value={hash,blockNumber:10,blockHash,index:0,type:2,chainId:9n,signature:'0x'+'00'.repeat(64),txInputs:[],txOutputs:[]};
test('published transaction refresh checks a Promise with instanceof and therefore returns null',async()=>{
 for(const Class of [QuaiTransactionResponse,QiTransactionResponse]){let calls=0;const provider={getTransaction:async()=>{calls++;return new Class(value,provider);},getBlockNumber:async()=>12};const response=new Class({...value,blockHash:null,blockNumber:null},provider);assert.equal(await response.getTransaction(),null);assert.equal(await response.confirmations(),0);assert.equal(calls,2);}
});
test('published response confirmations use arithmetic on stored inclusion without canonical rechecks',async()=>{
 for(const Class of [QuaiTransactionResponse,QiTransactionResponse]){const response=new Class(value,{getBlockNumber:async()=>8});assert.equal(response.isMined(),true);assert.equal(await response.confirmations(),-1);const copy=response.replaceableTransaction(100);assert.notEqual(copy,response);assert.equal(copy.hash,response.hash);assert.throws(()=>response.replaceableTransaction(-1));assert.equal(response.removedEvent().orphan,'drop-transaction');assert.equal(response.reorderedEvent(copy).orphan,'reorder-transaction');}
});
test('published Qi wait uses indexed transaction rather than an account receipt',async()=>{assert.equal(publicQuais.QiTransactionResponse,undefined);let reads=0;const provider={getTransaction:async()=>{reads++;return new QiTransactionResponse(value,provider);}};const response=new QiTransactionResponse(value,provider);const included=await response.wait(0,1);assert.equal(included.hash,hash);assert.equal(reads,1);assert.equal(response.toJSON()._type,'TransactionReceipt');});
test('contract transaction response inherits account fields and event payload listener removal is explicit',async()=>{const iface=new Interface(['event Ping(uint n)']);const response=new ContractTransactionResponse(iface,{}, {...value,type:0,from:'0x0011223344556677889900112233445566778899',sender:'claimed',originatingTxHash:hash,nonce:0,gasLimit:21000n,gasPrice:1n,value:0n,data:'0x'});assert.ok(response instanceof QuaiTransactionResponse);assert.equal(response.hash,hash);assert.equal(response.sender,undefined);assert.equal(response.originatingTxHash,undefined);let removed;const listener=()=>{};const emitter={off:async(...args)=>{removed=args;}};const payload=new EventPayload(emitter,listener,'Ping');assert.equal(payload.emitter,emitter);assert.equal(payload.filter,'Ping');await payload.removeListener();assert.deepEqual(removed,['Ping',listener]);});
