import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {Network,FeeData,HDNodeWallet,BIP44,SigningKey,pbkdf2,scrypt,scryptSync} from 'quais';
import {BaseWallet} from 'quais/wallet';
const f=JSON.parse(readFileSync(new URL('../fixtures/utility-completion.json',import.meta.url)));
test('published network labels IDs matches clones and registry remain metadata',()=>{for(const row of f.networks){const n=new Network(row.name,row.chainId);assert.deepEqual(n.toJSON(),row);assert.equal(n.matches({name:'different',chainId:BigInt(row.chainId)}),true);assert.equal(n.matches(row.chainId),true);const c=n.clone();c.name='changed';assert.equal(n.name,row.name);}assert.throws(()=>Network.from('unregistered-public-fixture'));Network.register('public-fixture',()=>new Network('canonical',987654321n));assert.equal(Network.from('public-fixture').chainId,987654321n);assert.throws(()=>Network.register('public-fixture',()=>new Network('other',1)));assert.equal(Network.from(987654322n).name,'unknown');});
test('published fee metadata exports exact strings and null',()=>{for(const row of f.fees){const r=new FeeData(row.gasPrice===null?null:BigInt(row.gasPrice));assert.deepEqual(r.toJSON(),row);}});
test('published BIP44 public derivation matches raw point/chain code and ignores account label for math',()=>{const n=f.publicNode;for(const row of n.children){assert.deepEqual(BIP44.deriveChildFromPublic(n.publicKey,n.chainCode,0,row.change,row.index),row.expected);const other=BIP44.deriveChildFromPublic(n.publicKey,n.chainCode,17,row.change,row.index);assert.equal(other.publicKey,row.expected.publicKey);assert.equal(other.chainCode,row.expected.chainCode);}const coin=HDNodeWallet.fromSeed(n.seed).derivePath("m/44'/969'");assert.equal(new BIP44(coin,969).xPub,coin.extendedKey);assert.ok(coin.extendedKey.startsWith('xprv'));});
test('published standalone PBKDF2 and sync/async scrypt vectors and progress',async()=>{assert.throws(()=>scryptSync('0x','0x',1,1,1,32));for(const row of f.kdfs){if(row.kind==='pbkdf2')assert.equal(pbkdf2(row.password,row.salt,row.rounds,row.length,row.hash),row.output);else{assert.equal(scryptSync(row.password,row.salt,2**row.logN,row.r,row.p,row.length),row.output);const fractions=[];assert.equal(await scrypt(row.password,row.salt,2**row.logN,row.r,row.p,row.length,n=>fractions.push(n)),row.output);assert.ok(fractions.length>1);assert.equal(fractions.at(-1),1);assert.ok(fractions.every((n,i)=>n>=0&&n<=1&&(!i||n>=fractions[i-1])));}}});
test('published minimal wallet explicit address override is not retained by connect',async()=>{const key=new SigningKey('0x'+'0'.repeat(60)+'0325');const wallet=new BaseWallet(key,null,'0x0000000000000000000000000000000000000001');assert.equal(await wallet.getAddress(),wallet.address);assert.notEqual(wallet.connect(null).address,wallet.address);assert.equal(wallet.signMessageSync('PUBLIC'),await wallet.signMessage('PUBLIC'));});
